#Configuracoes Ambiente
server.port = 8020

#Configuracao de conexao SQL-Server
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bkp_BancoScmThiago;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BancoScmThiago;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bkp_BancoScmThiagoPrincipal;encrypt=false;trustServerCertificate=true;sslProtocol=TLSv1.2
spring.datasource.username=sa
spring.datasource.password=13509
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Configuracoes HikariCP - Pool de Conexoes
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=ESCHikariPool

#Configuracoes Projeto
server.error.include-message=always
spring.main.allow-bean-definition-overriding=true

#Configuracoes Swagger/Springfox 3.0.0
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springfox.documentation.enabled=true

#Configuracoes Sessao
prop.tempoLimiteSessao=1440

#Configuracao Backup
prop.basePrincipal=BancoScmThiago
#prop.basePrincipal=bkp_BancoScmThiago
prop.baseBackup=bkp_BancoScmThiagoPrincipal